####################################
#          Section 1               #
####################################

# Browser
browser=(
    vivaldi
    librewolf
    tor
    firefox
    #ladybird
)

####################################
#          Section 2               #
####################################

# Media
media=(
    shortwave
    vlc
    mpv
    adacity
    kdenlive
    obs-studio
    ffmpeg
    stremio
    kodi
    shortwave
    jellyfin
    freetube
    jdownloader2
    yt-dlp
    kamoso
)

####################################
#          Section 3               #
####################################

# Communication
chat=(
    mumble
    discord
    viber
    telegram
)

####################################
#          Section 4               #
####################################

# Office & Productivity & Notes
productivity=(
    libreoffice # alternatives: onlyoffice
    obsidian # alternatives: logseq, zettlr, joplin, notesnook, standard notes
)

####################################
#          Section 5               #
####################################

# Utilities & Back-up
util=(
    #timeshift
)

####################################
#          Section 6               #
####################################

# File Sharing
transfer=(
    qbittorrent
    localsend
    fileZilla
    #warpinator
)

####################################
#          Section 7               #
####################################

# Audio
audio=(
    audacity
    elisa
    pipewire
    wireplumber
    helvum
    flac
    easyeffects
)

####################################
#          Section 8               #
####################################

# Games, Launchers, Emulators
games=(
    steam
    heroic
    space_cadet_pinball
    lutris
    hydra_launcher
    dolphin_emulator
    melonds
    rpcs3
    pcsx2
    retroarch
)


####################################
#          Section 9               #
####################################

# CLI
cli=(
    htop
    btop
    ghostty # alternative: alacritty, Kitty terminal
    fastfetch
    git
    nodejs
    npm
    python
    curl
    syncthing
    7z
    wget   
)

# Development
dev_tools=(
    tmux
    lazygit
    unrar
    zip
    unzip
    bat
    zsh
    neovim
)

####################################
#          Section 10              #
####################################

# Media Tools
mediatool=(
    mkvtoolnix
    makemkv
    #eac3to
)

# Desktop enviroment
desktop=(
    kde
)