####################################
#          Section 1               #
####################################

# Browser
browser=(
    vivaldi
    librewolf
    tor
    firefox
    #ladybird
)

####################################
#          Section 2               #
####################################

# Media
media=(
    shortwave
    vlc
    mpv
    adacity
    kdenlive
    obs-studio
    ffmpeg
    stremio
    kodi
    jellyfin
    freetube
    yt-dlp
    obs-studio
    iruin-webcam
    kamoso
)

####################################
#          Section 3               #
####################################

# Communication
chat=(
    mumble
    discord
    viber
    telegram
)

####################################
#          Section 4               #
####################################

# Office & Productivity & Notes
productivity=(
    libreoffice # alternatives: onlyoffice
    obsidian # alternatives: logseq, zettlr, joplin, notesnook, standard notes
)

####################################
#          Section 5               #
####################################

# Utilities & Back-up & System & More
util=(
    #timeshift, pika backup
    calibre
    blanket
    mission-center # alternative: resources
    jdownloader2
    peazip # alternatives: ark
    mullvadvpn
    rustdesk
    qemu
    okular
    qdirstat # alternatives: filelight
    qalculate! # alternatives: kcalc
    keepassxc # password manager
    gear-lever # appimage manager
    gparted # alternative: kde-partition-manager
    rustdesk # Remote Connection
    winboat # Windows vm
    virtualbox # Virtual machines
)

####################################
#          Section 6               #
####################################

# File Sharing
transfer=(
    qbittorrent
    localsend # alternative: warpinator
    fileZilla
)

####################################
#          Section 7               #
####################################

# Audio
audio=(
    audacity
    elisa
    pipewire
    wireplumber
    helvum
    flac
    easyeffects
)

####################################
#          Section 8               #
####################################

# Games, Launchers, Emulators
games=(
    steam
    heroic-games-launcher
    space-cadet-pinball
    lutris
    hydra-launcher
    dolphin-emulator
    melonds
    rpcs3
    pcsx2
    retroarch
    kmines
    kpatients
)


####################################
#          Section 9               #
####################################

# CLI
cli=(
    htop
    btop
    ghostty # alternative: alacritty, Kitty terminal
    fastfetch
    git
    nodejs
    npm
    python
    curl
    syncthing
    7z
    wget
    gh
    tmux
)

# Development
dev_tools=(
    tmux
    lazygit
    unrar
    zip
    unzip
    bat
    zsh
    neovim
    code #visual studio code
)

####################################
#          Section 10              #
####################################

# Media Tools
mediatool=(
    mkvtoolnix
    makemkv
    mediainfo
    #eac3to
)

####################################
#          Section 11              #
####################################

# Desktop enviroment
desktop=(
    kde
    color-picker
)

####################################
#          Section 12              #
####################################

# Art
art=(
    inkscape
    krita
    blender
)